# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae7f098102a8e8ad1f33a1feb06c600e454db2fb5cc6f7fa74903fafc2098ca9fb33dfff6e0f6b22d513f86176131ce85fc68cae0643a27dc19a7c4ba1532c17

test:
  secret_key_base: a45682faab030f4de13c61380b1b845951aef3ed4266d7d8e209b14e27758f4368477239b947a7b2452e50588b2bd9c0c6d9e33528f785d7bf137d8690ef1cce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
